name: Build Bisq 2

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize, closed ]
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ inputs.name }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: 'true'

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: build -x test
          build-root-directory: ${{ inputs.build-root-dir }}
          gradle-executable: ./gradlew
          gradle-version: 8.9

      # Add this new step to upload Linux packages
      - name: Upload Linux packages
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            ${{ inputs.build-root-dir }}/build/packaging/jpackage/packages/*.deb
            ${{ inputs.build-root-dir }}/build/packaging/jpackage/packages/*.rpm
            ${{ inputs.build-root-dir }}/build/packaging/jpackage/packages/aur/
          retention-days: 7